language: go

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - NAME=systemd 
        - DOCKER=true
    - os: linux
      dist: trusty
      sudo: required
      env: 
        - NAME=upstart
        - GO15VENDOREXPERIMENT=1
        - GO_SPFC_SUDO_TEST=true
      go: 1.5.3
    - os: osx
      language: generic
      env:
        - NAME=launchd 
        - GO15VENDOREXPERIMENT=1
install:
  - ./.travis/install.sh
script: .travis/build.sh
