language: go

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER=true
    - os: linux
      dist: trusty
      sudo: required
      env: GO15VENDOREXPERIMENT=1
      go: 1.5.3
    - os: osx
      language: generic
      env: GO15VENDOREXPERIMENT=1
install:
  - ./.travis/install.sh
script: .travis/build.sh
